# Package tweaks
- name: Faster dnf
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: true

- name: External repos
  include_role:
    name: fedora
    tasks_from: copr
  loop:
  - user: thelocehiliosan
    repo: yadm
  - user: copart
    repo: restic

- name: Basic packages
  dnf:
    name:
    - autojump
    - emacs
    - fzf
    - git
    - restic
    - the_silver_searcher
    - tmux
    - vim-enhanced
    - yadm
    state: latest

- name: Unwanted KDE packages
  dnf:
    name:
    - akgregator
    - kget
    - kmail
    - knode
    - konqueror
    - kontact
    state: absent

- name: dnf cleanup
  dnf:
    autoremove: yes

- name: Update pre-installed packages
  dnf:
    name: '*'
    state: latest

# ssh lockdown
- name: Disable Password Authentication
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
  - restart ssh

- name: Disable ChallengeResponse Authentication
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: "ChallengeResponseAuthentication no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
  - restart ssh

- name: Disable Root Login
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
    - restart ssh